## Word embeddings
#### Is the process of transforming words into vectors in a multi-dimensional space. The word are spread in the space in such a way that their distance corresponds to their semantic or lingutic similarity.

### Two main types
#### Frequency based embedding
#### Prediction based embedding

### Frequency based embedding
#### TF-IDF is a statistical measure used to evaluate the importance of a word to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus.

In [6]:
text=["the process of transforming words into vectors in a multi-dimensional space. The word are spread in the space in such a way that their distance corresponds to their semantic or lingutic similarity",
      "TF-IDF is a statistical measure used to evaluate the importance of a word to a document in a collection or corpus. The importance increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus"]
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
word_count=count.fit_transform(text)
print(word_count)

  (0, 35)	3
  (0, 25)	1
  (0, 22)	1
  (0, 39)	1
  (0, 44)	1
  (0, 16)	1
  (0, 41)	1
  (0, 14)	3
  (0, 20)	1
  (0, 7)	1
  (0, 29)	2
  (0, 43)	1
  (0, 1)	1
  (0, 30)	1
  (0, 32)	1
  (0, 42)	1
  (0, 34)	1
  (0, 36)	2
  (0, 8)	1
  (0, 6)	1
  (0, 38)	1
  (0, 27)	1
  (0, 24)	1
  (0, 18)	1
  (0, 28)	1
  :	:
  (1, 22)	3
  (1, 14)	3
  (1, 43)	3
  (1, 38)	3
  (1, 24)	1
  (1, 33)	1
  (1, 12)	1
  (1, 17)	2
  (1, 31)	1
  (1, 19)	1
  (1, 40)	1
  (1, 10)	1
  (1, 13)	2
  (1, 9)	2
  (1, 4)	1
  (1, 5)	2
  (1, 15)	1
  (1, 26)	1
  (1, 21)	1
  (1, 37)	1
  (1, 0)	1
  (1, 2)	1
  (1, 23)	1
  (1, 3)	1
  (1, 11)	1

In [4]:
print(word_count.toarray())

[[0 1 0 0 0 0 1 1 1 0 0 0 0 0 3 0 1 0 1 0 1 0 1 0 1 1 0 1 1 2 1 0 1 0 1 3
  2 0 1 1 0 1 1 1 1]
 [1 0 1 1 1 2 0 0 0 2 1 1 1 2 3 1 0 2 0 1 0 1 3 1 1 0 1 0 0 0 0 1 0 1 0 7
  0 1 3 0 1 0 0 3 0]]

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_transformer=TfidfTransformer(smooth_idf=True,use_idf=True)
tfidf_transformer.fit(word_count)
df_idf = pd.DataFrame(tfidf_transformer.idf_, columns=["idf_weights"])

df_idf.sort_values(by=['idf_weights'])

    idf_weights
22     1.000000
24     1.000000
14     1.000000
35     1.000000
38     1.000000
43     1.000000
37     1.405465
42     1.405465
25     1.405465
26     1.405465
27     1.405465
28     1.405465
29     1.405465
39     1.405465
41     1.405465
31     1.405465
23     1.405465
33     1.405465
34     1.405465
40     1.405465
36     1.405465
30     1.405465
32     1.405465
0      1.405465
20     1.405465
1      1.405465
2      1.405465
3      1.405465
4      1.405465
5      1.405465
6      1.405465
7      1.405465
8      1.405465
21     1.405465
9      1.405465
11     1.405465
12     1.405465
13     1.405465
15     1.405465
16     1.405465
17     1.405465
18     1.405465
19     1.405465
10     1.405465
44     1.405465